# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: '210215-usf-net'
    scannerMode: 'MSBuild'
    projectKey: '210215-USF-NET_GivHub-By-SHRKD'
    projectName: 'GivHub-By-SHRKD'
    extraProperties: |
      sonar.exclusions=**/lib/**
- task: DownloadSecureFile@1
  name: mySecureFile
  inputs:
    secureFile: 'appsettings.json'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: 'appsettings.json'
    TargetFolder: '$(System.DefaultWorkingDirectory)/SHRKD_GivHub/GivHubIntTests'
    OverWrite: true
- task: DownloadSecureFile@1
  name: mySecureFile2
  inputs:
    secureFile: 'appsettings.json'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: 'appsettings.json'
    TargetFolder: '$(System.DefaultWorkingDirectory)/SHRKD_GivHub/GivHubMoqTests'
    OverWrite: true
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/SHRKD_GivHub/*.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**SHRKD_GivHub/GivHubTests/*.csproj'
    arguments: --configuration $(buildConfiguration) --collect "Code Coverage"
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/coburtura/coverage.xml'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
    projects: '**/SHRKD_GivHub/SHRKD_GivHub/*.csproj'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(583825bd-d55a-497c-bfe6-2e3972e128e2)'
    appType: 'webApp'
    WebAppName: 'GivHubAPI'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    AppSettings: '-WEBSITE_RUN_FROM_PACKAGE 0'